version: "3.9"
services:
  mongodb:
    container_name: gallery_db
    image: mongo:latest
    restart: always
    command: [--auth]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_READ_WRITE_USER=${MONGO_READ_WRITE_USER}
      - MONGO_READ_WRITE_PASSWORD=${MONGO_READ_WRITE_PASSWORD}
      - MONGO_READ_USERNAME=${MONGO_READ_USERNAME}
      - MONGO_READ_PASSWORD=${MONGO_READ_PASSWORD}
      - MONGO_USER_READ_USERNAME=${MONGO_USER_READ_USERNAME}
      - MONGO_USER_READ_PASSWORD=${MONGO_USER_READ_PASSWORD}
      - MONGO_USER_ADMIN_USERNAME=${MONGO_USER_ADMIN_USERNAME}
      - MONGO_USER_ADMIN_PASSWORD=${MONGO_USER_ADMIN_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./db/data:/data/db
      - ./db/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    env_file: .env
