# echo -n 'testuser1:pwd123' | base64

@host = http://localhost
@port = 5000
@token = "TOKEN"

###

GET {{host}}:{{port}}/api/jwt/
Authorization: Basic dGVzdHVzZXIxOnB3ZDEyMw==

###

GET {{host}}:{{port}}/api/jwt/validate
Authorization: Bearer {{token}}
